server:
  port: 8889
  servlet:
    context-path: /lyq

spring:
  jackson:
    date-format: java.text.SimpleDateFormat
    default-property-inclusion: non_null
  application:
    name: backend
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  redis:
    host: 192.168.200.3
    port: 6379
    timeout: 30000
dubbo:
  registry:
    address: zookeeper://192.168.200.3:2182
    timeout: 25000
#  protocol:
#    name: dubbo
##    default: false
  scan:
    base-package: net.zjitc.controller
  application:
    id: backend
  consumer:
    check: false

#jedis :
#  pool :
#    host : 192.168.200.3
#    port : 6379
#    config :
#      maxTotal: 100
#      maxIdle: 10
#      maxWaitMillis : 100000

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#  type-aliases-package: net.zjitc.entity
#  mapper-locations: classpath:/net/zjitc/mapper/*.xml


#  servlet:
#    multipart:
#      max-request-size: 50MB
#      max-file-size: 50MB
      #    view:
      #      suffix: .html
      #  jackson:
      #    date-format: yyyy-MM-dd HH:mm:ss
      #    default-property-inclusion: non_null
#
#markerhub:
#  jwt:
#    header: Authorization
#    exprie: 604800
#    secret: sderftgyhijnhg67y8u4e3ws27896gt5







